---
name: Container Build & Push

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "!Dockerfile"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  run-hadolint:
    name: Hadolint Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

  trivy-scan:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          format: "table"
          ignore-unfixed: true
          scan-type: "config"
          severity: "CRITICAL,HIGH"
          trivyignores: ".trivyignore"

  test:
    needs: [run-hadolint, trivy-scan]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          load: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:${{ github.sha }}

      - name: Test
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:${{ github.sha }}

  dockerhub-push:
    needs: test
    name: Docker Hub Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPOSITORY }}:latest
